name: WorkFlow-production

on: [push, pull_request]


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: contains(
          github.event.ref
          , 'features') || 
        contains(
          github.event.ref
          , 'tannico')

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          git checkout develop
          git rebase ${{steps.extract_branch.outputs.branch}}
          git push origin develop
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - if:
        contains(
          github.event.ref
          , 'features')
      run: echo eureka
    
    
    - if: github.event.ref == 'releases/**'
      run: echo pallaoro
  
    - if: github.event.ref == 'releases/*'
      run: echo pallaoro

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - run: echo "${{steps.extract_branch.outputs.branch}} pushed"
    - run: env
  complete-workflow:
     name: complete workflow always but merged pr
     runs-on: ubuntu-latest
     if: github.event.pull_request.merged != true
     steps:
       - run: env
     
