name: WorkFlow-pr-release

on:
  pull_request:
    types: [merged]
    branches: 
      - 'releases/**'
      - 'master'


jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - run: echo "${{github.base.ref}} pull request triggered"
    - run: env
