name: WorkFlow-delete-branch

on:
  delete

jobs:
  
  trigger-workflow:
    name: Trigger workflow
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - run: env
      
      - run: echo "${{github.event.ref}} deleted"
      - run: echo "${GITHUB_REF} deleted"
      - run: echo "${GITHUB_BASE_REF} deleted"
      - run: echo "${{github.ref}} deleted"
      - run: echo "${{github.base.ref}} deleted"
