name: WorkFlow-production

on:
  push:
    branches: 
      - 'master'
      - 'features/**'
      - 'releases/**'
      - 'develop'


jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: contains(
          github.event.ref
          , 'features')
    steps:
      - name: checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          echo ${{github.event.ref}}
          git checkout develop
          git rebase features/111
          git push origin develop
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - if:
        contains(
          github.event.ref
          , 'features')
      run: echo eureka
    
    
    - if: github.event.ref == 'releases/**'
      run: echo pallaoro
  
    - if: github.event.ref == 'releases/*'
      run: echo pallaoro

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - run: echo "${{steps.extract_branch.outputs.branch}} pushed"
    - run: env
