name: WorkFlow-production

on:
  push:
    branches: 
      - 'master'
      - 'features/**'
      - 'releases/**'
      - 'develop'


jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - if:
        contains('
          refs/heads/develop
          refs/heads/features/
          ', github.ref)
      run: echo eureka
    - if: github.event.ref == "releases**"
      run: echo pallaoro
    
    - if: github.event.ref == 'releases/**'
      run: echo pallaoro
   
    - if: github.event.ref == "releases/*"
      run: echo pallaoro
  
    - if: github.event.ref == 'releases/*'
      run: echo pallaoro

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - run: echo "${{steps.extract_branch.outputs.branch}} pushed"
    - run: env
