name: WorkFlow-delete-branch

on:
  delete

jobs:
  
  trigger-workflow:
    name: Trigger workflow
    runs-on: ubuntu-latest
    steps:

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: Print branch deleted
        run: echo "${{steps.extract_branch.outputs.branch}} deleted"
      